// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgFHr36xDhrH3udfS_R7MkqMfmKOPsAZE',
    appId: '1:685620528539:web:4237518700dce1b5890d3e',
    messagingSenderId: '685620528539',
    projectId: 'mototax-flutter',
    authDomain: 'mototax-flutter.firebaseapp.com',
    databaseURL: 'https://mototax-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'mototax-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACivQHPIGljEjDpn7uOI1NKX322msXsmo',
    appId: '1:685620528539:android:e57459d8c82641df890d3e',
    messagingSenderId: '685620528539',
    projectId: 'mototax-flutter',
    databaseURL: 'https://mototax-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'mototax-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJGnSyP3gqwwfGgM_EpYQPJ4BRZ2vClak',
    appId: '1:685620528539:ios:2ddba3fed32c8e8b890d3e',
    messagingSenderId: '685620528539',
    projectId: 'mototax-flutter',
    databaseURL: 'https://mototax-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'mototax-flutter.appspot.com',
    iosBundleId: 'com.rockstone.userApp',
  );
}
